// @generated by tools/gen_appstore_http_route_manifest.py - do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/publishers",
        "appstore",
        "appstore.publishers.admin.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/publishers/{publisherId}/verify",
        "appstore",
        "appstore.publishers.admin.verify",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
