// @generated by tools/gen_appstore_http_route_manifest.py - do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::public(
        HttpMethod::Get,
        "/store/v3/api/user-stores/{shareToken}",
        "appstore",
        "appstore.userStores.public.retrieve",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/store/v3/api/user-stores/{shareToken}/categories/{userCategoryId}/items",
        "appstore",
        "appstore.userStores.public.items.list",
    ),
];

pub fn open_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
