//! `appstore_*` table registry for repository implementation.
//!
//! Mirrors the full migration chain (folded baseline `0001_appstore_baseline.sql`
//! including the folded 0002 platform-evolution and 0005 web-store tables, plus
//! the 0003 user-store and 0004 SKU migrations) so the registry matches the
//! live schema: 74 tables total.

pub const APPSTORE_TABLES: &[&str] = &[
    "appstore_idempotency_key",
    "appstore_publisher",
    "appstore_publisher_member",
    "appstore_publisher_verification",
    "appstore_app",
    "appstore_app_dependency",
    "appstore_category",
    "appstore_category_localization",
    "appstore_tag",
    "appstore_tag_localization",
    "appstore_listing",
    "appstore_listing_localization",
    "appstore_listing_media",
    "appstore_listing_category_binding",
    "appstore_listing_tag_binding",
    "appstore_regional_availability",
    "appstore_compliance_profile",
    "appstore_compliance_permission_disclosure",
    "appstore_release_channel",
    "appstore_release",
    "appstore_release_note_localization",
    "appstore_release_artifact",
    "appstore_release_rollout",
    "appstore_market_channel",
    "appstore_market_release",
    "appstore_listing_submission",
    "appstore_moderation_review",
    "appstore_moderation_decision",
    "appstore_catalog_collection",
    "appstore_catalog_collection_localization",
    "appstore_catalog_collection_item",
    "appstore_catalog_featured_slot",
    "appstore_catalog_chart_snapshot",
    "appstore_user_library_item",
    "appstore_user_wishlist_item",
    "appstore_entitlement",
    "appstore_download_grant",
    "appstore_install_event",
    "appstore_listing_metric_snapshot",
    "appstore_app_template",
    "appstore_app_template_usage",
    "appstore_app_template_version",
    "appstore_catalog_search_history",
    "appstore_catalog_trending_term",
    "appstore_listing_iap_item",
    "appstore_listing_rating",
    "appstore_feedback",
    "appstore_moderation_appeal",
    "appstore_release_beta_invite",
    // Folded platform evolution — CREATE TABLE statements live in the folded
    // baseline (0001) and migration 0002 re-asserts them idempotently.
    "appstore_platform_dictionary",
    "appstore_app_platform",
    "appstore_platform_release",
    "appstore_signing_credential",
    "appstore_listing_review",
    "appstore_listing_review_vote",
    "appstore_listing_review_report",
    "appstore_rating_distribution_snapshot",
    "appstore_listing_price",
    "appstore_promo_code_batch",
    "appstore_promo_code",
    "appstore_release_tester_group",
    "appstore_release_tester_group_member",
    "appstore_catalog_search_doc",
    "appstore_analytics_metric_daily",
    // Web cluster stores (migration 0005).
    "appstore_web_rate_limit_bucket",
    "appstore_web_idempotency_entry",
    // User store domain (migration 0003).
    "appstore_user_category",
    "appstore_user_category_item",
    "appstore_user_store_share",
    // App SKU and deployment binding (migration 0004).
    "appstore_app_sku",
    "appstore_app_sku_attribute",
    "appstore_app_sku_model",
    "appstore_app_sku_contributor",
    "appstore_app_deployment_binding",
];
