#!/usr/bin/env python3
"""Generate combined appstore standalone-gateway http_route_manifest.rs."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

APP_CRATES = [
    "sdkwork-routes-appstore-catalog-app-api",
    "sdkwork-routes-compliance-app-api",
    "sdkwork-routes-library-app-api",
    "sdkwork-routes-publisher-app-api",
    "sdkwork-routes-release-app-api",
    "sdkwork-routes-listing-app-api",
    "sdkwork-routes-user-store-app-api",
]

BACKEND_CRATES = [
    "sdkwork-routes-appstore-catalog-backend-api",
    "sdkwork-routes-listing-backend-api",
    "sdkwork-routes-publisher-backend-api",
    "sdkwork-routes-moderation-backend-api",
    "sdkwork-routes-market-backend-api",
    "sdkwork-routes-metrics-backend-api",
]

OPEN_CRATES = [
    "sdkwork-routes-appstore-catalog-open-api",
    "sdkwork-routes-listing-open-api",
    "sdkwork-routes-release-open-api",
    "sdkwork-routes-automation-open-api",
    "sdkwork-routes-user-store-open-api",
]

ROUTE_ENTRY = re.compile(
    r"HttpRoute::(\w+)\(\s*"
    r"HttpMethod::(\w+),\s*"
    r'"([^"]+)",\s*'
    r'"([^"]+)",\s*'
    r'"([^"]+)",\s*'
    # The final route of a per-crate manifest closes with `)]` (no trailing
    # comma); tolerate both `),` and `)` so no entry is silently dropped.
    r"\)\s*,?",
    re.MULTILINE,
)

PUBLIC_PREFIXES_SNIPPET = """pub fn appstore_public_path_prefixes() -> Vec<String> {
    sdkwork_web_bootstrap::infra_public_path_prefixes()
}"""


def extract_http_routes(manifest_path: Path) -> list[str]:
    if not manifest_path.exists():
        return []
    text = manifest_path.read_text(encoding="utf-8")
    blocks: list[str] = []
    for auth, method, path, tag, op in ROUTE_ENTRY.findall(text):
        blocks.append(
            "\n".join(
                [
                    f"    HttpRoute::{auth}(",
                    f"        HttpMethod::{method},",
                    f'        "{path}",',
                    f'        "{tag}",',
                    f'        "{op}",',
                    "    ),",
                ]
            )
        )
    return blocks


def main() -> None:
    blocks: list[str] = []
    for crate in APP_CRATES + BACKEND_CRATES + OPEN_CRATES:
        manifest = ROOT / "crates" / crate / "src" / "http_route_manifest.rs"
        blocks.extend(extract_http_routes(manifest))

    if not blocks:
        raise SystemExit("no routes extracted for combined manifest")

    output = "\n".join(
        [
            "// @generated by tools/gen_appstore_combined_http_route_manifest.py - do not edit",
            "",
            "use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};",
            "",
            "const HTTP_ROUTES: &[HttpRoute] = &[",
            *blocks,
            "];",
            "",
            "pub fn appstore_route_manifest() -> HttpRouteManifest {",
            "    HttpRouteManifest::new(HTTP_ROUTES)",
            "}",
            "",
            PUBLIC_PREFIXES_SNIPPET,
            "",
            "pub fn appstore_open_api_prefixes() -> Vec<String> {",
            '    vec!["/store/v3/api".to_owned()]',
            "}",
            "",
        ]
    )

    out_path = ROOT / "crates" / "sdkwork-api-appstore-assembly" / "src" / "http_route_manifest.rs"
    out_path.write_text(output, encoding="utf-8")
    print(f"wrote {len(blocks)} routes to {out_path}")


if __name__ == "__main__":
    main()
