-- SDKWork appstore consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_appstore_baseline.sql
-- SDKWork appstore consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_appstore_legacy_baseline.sql
-- Consolidated legacy baseline imported by bootstrap-database-module.mjs
-- Review and replace with contract-first migrations.

-- source: specs/database/migrations/0001_appstore_foundation.sql
-- SDKWork App Store foundation schema
-- Domain: appstore | Prefix: appstore_ | Compliance: L2 (selected L3 tables noted)
-- Derived from specs/database/schema-registry.yaml

CREATE TABLE IF NOT EXISTS appstore_idempotency_key (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  response_json TEXT,
  status TEXT NOT NULL,
  locked_until TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, scope, idempotency_key)
);

CREATE TABLE IF NOT EXISTS appstore_publisher (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  publisher_no TEXT NOT NULL,
  publisher_type TEXT NOT NULL,
  display_name TEXT NOT NULL,
  legal_name TEXT,
  publisher_status TEXT NOT NULL,
  verification_status TEXT NOT NULL,
  contact_snapshot_json TEXT NOT NULL DEFAULT '{}',
  profile_snapshot_json TEXT NOT NULL DEFAULT '{}',
  website_url TEXT,
  support_email TEXT,
  logo_media_resource_id TEXT,
  owner_user_id TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 0,
  verified_at TIMESTAMPTZ,
  suspended_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, publisher_no),
  UNIQUE (tenant_id, organization_id, owner_user_id)
);

CREATE TABLE IF NOT EXISTS appstore_publisher_member (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  publisher_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  member_role TEXT NOT NULL,
  member_status TEXT NOT NULL,
  invited_by TEXT,
  joined_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, publisher_id, user_id)
);

CREATE TABLE IF NOT EXISTS appstore_publisher_verification (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  publisher_id TEXT NOT NULL,
  verification_type TEXT NOT NULL,
  verification_status TEXT NOT NULL,
  credential_snapshot_json TEXT NOT NULL DEFAULT '{}',
  evidence_media_resource_id TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, publisher_id, verification_type)
);

CREATE TABLE IF NOT EXISTS appstore_app (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  publisher_id TEXT NOT NULL,
  app_no TEXT NOT NULL,
  app_key TEXT NOT NULL,
  app_slug TEXT NOT NULL,
  display_name TEXT NOT NULL,
  default_locale TEXT NOT NULL,
  app_type TEXT NOT NULL,
  runtime_family TEXT NOT NULL,
  runtime_framework TEXT NOT NULL,
  app_status TEXT NOT NULL,
  distribution_status TEXT NOT NULL,
  review_status TEXT NOT NULL,
  monetization_mode TEXT NOT NULL,
  primary_category_id TEXT,
  secondary_category_id TEXT,
  age_rating_code TEXT,
  content_rating_json TEXT NOT NULL DEFAULT '{}',
  official_website_url TEXT,
  support_url TEXT,
  privacy_policy_url TEXT,
  terms_url TEXT,
  icon_media_id TEXT,
  icon TEXT NOT NULL DEFAULT '{}',
  icon_resource_snapshot TEXT NOT NULL DEFAULT '',
  resource_list TEXT NOT NULL DEFAULT '[]',
  access_url TEXT,
  config TEXT NOT NULL DEFAULT '{}',
  runtime_status INTEGER NOT NULL DEFAULT 1,
  install_skill TEXT NOT NULL DEFAULT '{}',
  install_config TEXT NOT NULL DEFAULT '{}',
  install_platforms TEXT NOT NULL DEFAULT '[]',
  platforms TEXT NOT NULL DEFAULT '[]',
  release_notes TEXT NOT NULL DEFAULT '[]',
  package_name TEXT,
  bundle_id TEXT,
  store_url TEXT,
  artifact_resource_snapshot TEXT NOT NULL DEFAULT '',
  download_count INTEGER NOT NULL DEFAULT 0,
  rating_avg TEXT NOT NULL DEFAULT '0',
  rating_count INTEGER NOT NULL DEFAULT 0,
  legacy_uuid TEXT,
  owner_user_id TEXT,
  project_id TEXT,
  description TEXT,
  current_listing_id TEXT,
  current_release_id TEXT,
  latest_released_version TEXT,
  manifest_snapshot_json TEXT NOT NULL DEFAULT '{}',
  version INTEGER NOT NULL DEFAULT 0,
  submitted_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  released_at TIMESTAMPTZ,
  suspended_at TIMESTAMPTZ,
  retired_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, app_no),
  UNIQUE (tenant_id, app_key),
  UNIQUE (tenant_id, app_slug)
);

CREATE TABLE IF NOT EXISTS appstore_app_dependency (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  app_id TEXT NOT NULL,
  dependency_app_id TEXT,
  dependency_key TEXT NOT NULL,
  dependency_kind TEXT NOT NULL,
  version_requirement TEXT,
  dependency_status TEXT NOT NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, app_id, dependency_key, dependency_kind)
);

CREATE TABLE IF NOT EXISTS appstore_category (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  category_code TEXT NOT NULL,
  parent_category_id TEXT,
  category_level INTEGER NOT NULL DEFAULT 1,
  category_status TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  icon_media_resource_id TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, category_code)
);

CREATE TABLE IF NOT EXISTS appstore_category_localization (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  category_id TEXT NOT NULL,
  locale TEXT NOT NULL,
  display_name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, category_id, locale)
);

CREATE TABLE IF NOT EXISTS appstore_tag (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  tag_code TEXT NOT NULL,
  tag_type TEXT NOT NULL,
  tag_status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, tag_code)
);

CREATE TABLE IF NOT EXISTS appstore_tag_localization (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  tag_id TEXT NOT NULL,
  locale TEXT NOT NULL,
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, tag_id, locale)
);

CREATE TABLE IF NOT EXISTS appstore_listing (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  publisher_id TEXT NOT NULL,
  listing_no TEXT NOT NULL,
  app_id TEXT NOT NULL,
  app_key TEXT NOT NULL,
  listing_slug TEXT NOT NULL,
  listing_type TEXT NOT NULL,
  pricing_model TEXT NOT NULL,
  listing_status TEXT NOT NULL,
  storefront_visibility TEXT NOT NULL,
  review_status TEXT NOT NULL,
  primary_category_id TEXT,
  default_locale TEXT NOT NULL,
  age_rating_code TEXT,
  content_rating_json TEXT NOT NULL DEFAULT '{}',
  official_website_url TEXT,
  support_url TEXT,
  privacy_policy_url TEXT,
  comments_thread_id TEXT,
  commerce_product_id TEXT,
  current_release_id TEXT,
  featured_score INTEGER NOT NULL DEFAULT 0,
  download_count INTEGER NOT NULL DEFAULT 0,
  average_rating TEXT,
  rating_count INTEGER NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  submitted_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  delisted_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, listing_no),
  UNIQUE (tenant_id, app_id),
  UNIQUE (tenant_id, listing_slug)
);

CREATE TABLE IF NOT EXISTS appstore_listing_localization (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  listing_id TEXT NOT NULL,
  locale TEXT NOT NULL,
  display_name TEXT NOT NULL,
  subtitle TEXT,
  short_description TEXT NOT NULL,
  full_description TEXT NOT NULL,
  whats_new_summary TEXT,
  keywords_json TEXT NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, listing_id, locale)
);

CREATE TABLE IF NOT EXISTS appstore_listing_media (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  listing_id TEXT NOT NULL,
  media_role TEXT NOT NULL,
  media_resource_id TEXT NOT NULL,
  drive_node_id TEXT,
  platform_scope TEXT NOT NULL DEFAULT 'ALL',
  sort_order INTEGER NOT NULL DEFAULT 0,
  locale TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, listing_id, media_role, sort_order, locale)
);

CREATE TABLE IF NOT EXISTS appstore_listing_category_binding (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  category_id TEXT NOT NULL,
  is_primary INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, listing_id, category_id)
);

CREATE TABLE IF NOT EXISTS appstore_listing_tag_binding (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  tag_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, listing_id, tag_id)
);

CREATE TABLE IF NOT EXISTS appstore_regional_availability (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  listing_id TEXT NOT NULL,
  region_code TEXT NOT NULL,
  availability_status TEXT NOT NULL,
  effective_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, listing_id, region_code)
);

CREATE TABLE IF NOT EXISTS appstore_compliance_profile (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  listing_id TEXT NOT NULL,
  compliance_version INTEGER NOT NULL DEFAULT 1,
  privacy_nutrition_json TEXT NOT NULL DEFAULT '{}',
  content_rating_questionnaire_json TEXT NOT NULL DEFAULT '{}',
  data_safety_json TEXT NOT NULL DEFAULT '{}',
  target_audience_json TEXT NOT NULL DEFAULT '{}',
  compliance_status TEXT NOT NULL,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, listing_id, compliance_version)
);

CREATE TABLE IF NOT EXISTS appstore_compliance_permission_disclosure (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  listing_id TEXT NOT NULL,
  permission_code TEXT NOT NULL,
  usage_purpose TEXT NOT NULL,
  is_required INTEGER NOT NULL DEFAULT 1,
  disclosure_status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, listing_id, permission_code)
);

CREATE TABLE IF NOT EXISTS appstore_release_channel (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  channel_code TEXT NOT NULL,
  channel_type TEXT NOT NULL,
  channel_status TEXT NOT NULL,
  audience_scope TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, channel_code)
);

CREATE TABLE IF NOT EXISTS appstore_release (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  listing_id TEXT NOT NULL,
  release_no TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  version_name TEXT NOT NULL,
  version_code TEXT NOT NULL,
  build_number TEXT,
  release_status TEXT NOT NULL,
  minimum_os_version TEXT,
  release_notes_default_locale TEXT,
  manifest_snapshot_json TEXT NOT NULL DEFAULT '{}',
  submitted_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  retired_at TIMESTAMPTZ,
  version INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, release_no),
  UNIQUE (tenant_id, listing_id, channel_id, version_code)
);

CREATE TABLE IF NOT EXISTS appstore_release_note_localization (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  release_id TEXT NOT NULL,
  locale TEXT NOT NULL,
  release_notes TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, release_id, locale)
);

CREATE TABLE IF NOT EXISTS appstore_release_artifact (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  release_id TEXT NOT NULL,
  artifact_no TEXT NOT NULL,
  platform TEXT NOT NULL,
  architecture TEXT NOT NULL,
  package_format TEXT NOT NULL,
  artifact_status TEXT NOT NULL,
  drive_node_id TEXT NOT NULL,
  media_resource_id TEXT,
  file_size_bytes TEXT NOT NULL,
  content_type TEXT NOT NULL,
  checksum_sha256 TEXT NOT NULL,
  signature_snapshot_json TEXT NOT NULL DEFAULT '{}',
  sbom_ref TEXT,
  provenance_ref TEXT,
  min_os_version TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, artifact_no),
  UNIQUE (tenant_id, release_id, platform, architecture, package_format)
);

CREATE TABLE IF NOT EXISTS appstore_release_rollout (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  release_id TEXT NOT NULL,
  rollout_strategy TEXT NOT NULL,
  rollout_status TEXT NOT NULL,
  target_percentage INTEGER NOT NULL DEFAULT 100,
  current_percentage INTEGER NOT NULL DEFAULT 0,
  region_filter_json TEXT NOT NULL DEFAULT '[]',
  device_filter_json TEXT NOT NULL DEFAULT '{}',
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  paused_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, release_id)
);

CREATE TABLE IF NOT EXISTS appstore_market_channel (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  channel_code TEXT NOT NULL,
  channel_type TEXT NOT NULL,
  provider TEXT NOT NULL,
  channel_status TEXT NOT NULL,
  external_store_code TEXT,
  api_capability_json TEXT NOT NULL DEFAULT '{}',
  config_json TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, channel_code)
);

CREATE TABLE IF NOT EXISTS appstore_market_release (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  app_id TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  release_id TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  market_release_no TEXT NOT NULL,
  external_app_id TEXT,
  external_release_id TEXT,
  external_track TEXT,
  market_status TEXT NOT NULL,
  rollout_percent INTEGER,
  countries_json TEXT NOT NULL DEFAULT '[]',
  store_url TEXT,
  external_status_json TEXT NOT NULL DEFAULT '{}',
  submitted_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  released_at TIMESTAMPTZ,
  rejected_at TIMESTAMPTZ,
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, market_release_no),
  UNIQUE (tenant_id, release_id, channel_id)
);

CREATE TABLE IF NOT EXISTS appstore_listing_submission (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  listing_id TEXT NOT NULL,
  release_id TEXT,
  submission_no TEXT NOT NULL,
  submission_type TEXT NOT NULL,
  submission_status TEXT NOT NULL,
  submitted_by TEXT NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL,
  payload_snapshot_json TEXT NOT NULL DEFAULT '{}',
  idempotency_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, submission_no),
  UNIQUE (tenant_id, listing_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS appstore_moderation_review (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  submission_id TEXT NOT NULL,
  review_no TEXT NOT NULL,
  review_status TEXT NOT NULL,
  priority TEXT NOT NULL,
  assigned_to TEXT,
  queue_code TEXT NOT NULL,
  sla_due_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, review_no),
  UNIQUE (tenant_id, submission_id)
);

CREATE TABLE IF NOT EXISTS appstore_moderation_decision (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  review_id TEXT NOT NULL,
  decision_no TEXT NOT NULL,
  decision_type TEXT NOT NULL,
  decision_status TEXT NOT NULL,
  reason_code TEXT,
  reason_detail TEXT,
  policy_reference TEXT,
  decided_by TEXT NOT NULL,
  decided_at TIMESTAMPTZ NOT NULL,
  payload_snapshot_json TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, decision_no)
);

CREATE TABLE IF NOT EXISTS appstore_catalog_collection (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  collection_code TEXT NOT NULL,
  collection_type TEXT NOT NULL,
  collection_status TEXT NOT NULL,
  audience_scope TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  cover_media_resource_id TEXT,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, collection_code)
);

CREATE TABLE IF NOT EXISTS appstore_catalog_collection_localization (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  collection_id TEXT NOT NULL,
  locale TEXT NOT NULL,
  display_name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, collection_id, locale)
);

CREATE TABLE IF NOT EXISTS appstore_catalog_collection_item (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  collection_id TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  highlight_json TEXT NOT NULL DEFAULT '{}',
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, collection_id, listing_id)
);

CREATE TABLE IF NOT EXISTS appstore_catalog_featured_slot (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  slot_code TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  slot_status TEXT NOT NULL,
  audience_scope TEXT NOT NULL,
  platform_scope TEXT NOT NULL DEFAULT 'ALL',
  region_scope_json TEXT NOT NULL DEFAULT '[]',
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, slot_code, starts_at)
);

CREATE TABLE IF NOT EXISTS appstore_catalog_chart_snapshot (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  chart_code TEXT NOT NULL,
  snapshot_date TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'en-US',
  platform_scope TEXT NOT NULL DEFAULT 'ALL',
  ranking_json TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, chart_code, snapshot_date, locale, platform_scope)
);

CREATE TABLE IF NOT EXISTS appstore_user_library_item (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  app_key TEXT NOT NULL,
  library_status TEXT NOT NULL,
  installed_release_id TEXT,
  installed_version_code TEXT,
  install_source TEXT NOT NULL,
  platform TEXT NOT NULL,
  architecture TEXT,
  device_id TEXT,
  last_checked_at TIMESTAMPTZ,
  installed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL,
  removed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, user_id, app_key, platform)
);

CREATE TABLE IF NOT EXISTS appstore_user_wishlist_item (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  wishlist_status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, user_id, listing_id)
);

CREATE TABLE IF NOT EXISTS appstore_entitlement (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  app_id TEXT NOT NULL,
  listing_id TEXT,
  subject_type TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  entitlement_type TEXT NOT NULL,
  source_type TEXT NOT NULL,
  entitlement_status TEXT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ,
  grant_snapshot_json TEXT NOT NULL DEFAULT '{}',
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, app_id, subject_type, subject_id, entitlement_type)
);

CREATE TABLE IF NOT EXISTS appstore_download_grant (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  grant_no TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  release_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  user_id TEXT,
  grant_status TEXT NOT NULL,
  grant_reason TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  download_count INTEGER NOT NULL DEFAULT 0,
  max_download_count INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, grant_no)
);

CREATE TABLE IF NOT EXISTS appstore_install_event (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  event_no TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  release_id TEXT,
  artifact_id TEXT,
  user_id TEXT,
  device_id TEXT,
  event_type TEXT NOT NULL,
  platform TEXT NOT NULL,
  architecture TEXT,
  event_status TEXT NOT NULL,
  source_channel TEXT,
  client_version TEXT,
  region_code TEXT,
  payload_snapshot_json TEXT NOT NULL DEFAULT '{}',
  occurred_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, event_no)
);

CREATE TABLE IF NOT EXISTS appstore_listing_metric_snapshot (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  listing_id TEXT NOT NULL,
  snapshot_date TEXT NOT NULL,
  impression_count INTEGER NOT NULL DEFAULT 0,
  detail_view_count INTEGER NOT NULL DEFAULT 0,
  install_count INTEGER NOT NULL DEFAULT 0,
  uninstall_count INTEGER NOT NULL DEFAULT 0,
  update_count INTEGER NOT NULL DEFAULT 0,
  conversion_rate TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (tenant_id, listing_id, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_appstore_listing_catalog
  ON appstore_listing (tenant_id, listing_status, storefront_visibility, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_appstore_app_status
  ON appstore_app (tenant_id, organization_id, distribution_status, review_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_appstore_listing_publisher
  ON appstore_listing (tenant_id, publisher_id, listing_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_appstore_release_update_check
  ON appstore_release (tenant_id, listing_id, release_status, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_appstore_release_artifact_lookup
  ON appstore_release_artifact (tenant_id, release_id, platform, architecture, artifact_status);

CREATE INDEX IF NOT EXISTS idx_appstore_market_release_status
  ON appstore_market_release (tenant_id, channel_id, market_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_appstore_user_library
  ON appstore_user_library_item (tenant_id, user_id, library_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_appstore_entitlement_subject
  ON appstore_entitlement (tenant_id, subject_type, subject_id, entitlement_status, expires_at);

CREATE INDEX IF NOT EXISTS idx_appstore_moderation_queue
  ON appstore_moderation_review (tenant_id, review_status, priority, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_appstore_download_grant_active
  ON appstore_download_grant (tenant_id, artifact_id, grant_status, expires_at);

CREATE INDEX IF NOT EXISTS idx_appstore_install_event_listing
  ON appstore_install_event (tenant_id, listing_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS appstore_app_template (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    template_no VARCHAR(64),
    template_code VARCHAR(128),
    template_name VARCHAR(255),
    description TEXT,
    category_id BIGINT,
    category_code VARCHAR(128),
    template_type VARCHAR(64),
    runtime VARCHAR(128),
    framework VARCHAR(128),
    language VARCHAR(64),
    icon_media_resource_id VARCHAR(128),
    icon_object_blob_id BIGINT,
    icon_resource_snapshot JSONB,
    cover_media_resource_id VARCHAR(128),
    cover_object_blob_id BIGINT,
    cover_resource_snapshot JSONB,
    visibility INTEGER,
    publish_status INTEGER,
    featured BOOLEAN,
    sort_weight INTEGER,
    owner_user_id BIGINT,
    source_app_id BIGINT,
    git_repo_url VARCHAR(1024),
    git_ref VARCHAR(128),
    git_sub_path VARCHAR(1024),
    current_version_id BIGINT,
    app_config_schema JSONB,
    default_app_config JSONB,
    variable_schema JSONB,
    dependency_manifest JSONB,
    capability_manifest JSONB,
    published_at TIMESTAMPTZ,
    deprecated_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_appstore_app_template_no ON appstore_app_template (tenant_id, template_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_appstore_app_template_code ON appstore_app_template (tenant_id, organization_id, template_code);
CREATE INDEX IF NOT EXISTS idx_appstore_app_template_scope_status ON appstore_app_template (tenant_id, organization_id, visibility, publish_status, status, updated_at, id);
CREATE INDEX IF NOT EXISTS idx_appstore_app_template_category ON appstore_app_template (tenant_id, organization_id, category_id, publish_status, sort_weight, id);

CREATE TABLE IF NOT EXISTS appstore_app_template_version (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    template_id BIGINT,
    version_no VARCHAR(64),
    artifact_id BIGINT,
    changelog TEXT,
    file_manifest JSONB,
    dependency_manifest JSONB,
    capability_manifest JSONB,
    variable_schema JSONB,
    app_config_schema JSONB,
    default_app_config JSONB,
    publish_status INTEGER,
    published_at TIMESTAMPTZ,
    deprecated_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_appstore_app_template_version_no ON appstore_app_template_version (tenant_id, organization_id, template_id, version_no);
CREATE INDEX IF NOT EXISTS idx_appstore_app_template_version_template ON appstore_app_template_version (tenant_id, organization_id, template_id, publish_status, created_at, id);

CREATE TABLE IF NOT EXISTS appstore_app_template_usage (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT,
    request_id VARCHAR(128),
    trace_id VARCHAR(128),
    payload_hash VARCHAR(128),
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retention_until TIMESTAMPTZ,
    legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    template_id BIGINT,
    template_version_id BIGINT,
    target_app_id BIGINT,
    usage_type INTEGER,
    input_snapshot JSONB,
    output_snapshot JSONB,
    UNIQUE (tenant_id, user_id, template_id, usage_type)
);

CREATE INDEX IF NOT EXISTS idx_appstore_app_template_usage_template ON appstore_app_template_usage (tenant_id, organization_id, template_id, template_version_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_appstore_app_template_usage_target ON appstore_app_template_usage (tenant_id, organization_id, target_app_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_appstore_app_template_usage_user ON appstore_app_template_usage (tenant_id, organization_id, user_id, created_at, id);

-- folded migration: migrations/postgres/0002_appstore_extensions.up.sql
-- SDKWork App Store extension schema
-- Domain: appstore | Prefix: appstore_ | Compliance: L2 (selected L3 tables noted)
-- Extends 0001_appstore_foundation.sql with search, appeals, IAP, beta, and template tables

CREATE TABLE IF NOT EXISTS appstore_listing_iap_item (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  listing_id TEXT NOT NULL,
  iap_no TEXT NOT NULL,
  iap_type TEXT NOT NULL,
  sku TEXT NOT NULL,
  display_name TEXT NOT NULL,
  price_cents INTEGER NOT NULL DEFAULT 0,
  currency_code TEXT NOT NULL DEFAULT 'USD',
  subscription_period TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, listing_id, iap_no),
  UNIQUE (tenant_id, listing_id, sku)
);

CREATE INDEX IF NOT EXISTS idx_appstore_listing_iap_item_listing
  ON appstore_listing_iap_item (tenant_id, listing_id, status);

CREATE TABLE IF NOT EXISTS appstore_catalog_search_history (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  query_text TEXT NOT NULL,
  filters_json TEXT NOT NULL DEFAULT '{}',
  result_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_appstore_catalog_search_history_user
  ON appstore_catalog_search_history (tenant_id, user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS appstore_catalog_trending_term (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  term TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'en',
  rank INTEGER NOT NULL,
  score REAL NOT NULL DEFAULT 0,
  snapshot_date TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, term, locale, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_appstore_catalog_trending_term_snapshot
  ON appstore_catalog_trending_term (tenant_id, snapshot_date, rank);

CREATE TABLE IF NOT EXISTS appstore_moderation_appeal (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  decision_id TEXT NOT NULL,
  review_id TEXT NOT NULL,
  appeal_no TEXT NOT NULL,
  appellant_user_id TEXT NOT NULL,
  appeal_reason TEXT NOT NULL,
  appeal_status TEXT NOT NULL DEFAULT 'pending',
  decided_by TEXT,
  decision_note TEXT,
  submitted_at TEXT NOT NULL,
  decided_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, appeal_no)
);

CREATE INDEX IF NOT EXISTS idx_appstore_moderation_appeal_status
  ON appstore_moderation_appeal (tenant_id, appeal_status, submitted_at);

CREATE INDEX IF NOT EXISTS idx_appstore_moderation_appeal_decision
  ON appstore_moderation_appeal (tenant_id, decision_id);

CREATE TABLE IF NOT EXISTS appstore_release_beta_invite (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  release_id TEXT NOT NULL,
  invitee_user_id TEXT,
  invitee_email TEXT,
  invite_status TEXT NOT NULL DEFAULT 'pending',
  invited_by TEXT NOT NULL,
  invited_at TEXT NOT NULL,
  accepted_at TEXT,
  revoked_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, release_id, invitee_email)
);

CREATE INDEX IF NOT EXISTS idx_appstore_release_beta_invite_release
  ON appstore_release_beta_invite (tenant_id, release_id, invite_status);



CREATE INDEX IF NOT EXISTS idx_appstore_app_template_status
  ON appstore_app_template (tenant_id, status, updated_at DESC);



CREATE INDEX IF NOT EXISTS idx_appstore_app_template_usage_template
  ON appstore_app_template_usage (tenant_id, template_id);



CREATE INDEX IF NOT EXISTS idx_appstore_app_template_version_template
  ON appstore_app_template_version (tenant_id, template_id, status);

-- folded migration: migrations/postgres/0003_appstore_rating_feedback.up.sql
-- 0003_appstore_rating_feedback.up.sql
-- Listing ratings (storefront star ratings + review title) and user feedback.

CREATE TABLE IF NOT EXISTS appstore_listing_rating (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  listing_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  rating INTEGER NOT NULL,
  title TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, listing_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_appstore_listing_rating_listing
  ON appstore_listing_rating (tenant_id, listing_id, created_at DESC);

CREATE TABLE IF NOT EXISTS appstore_feedback (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  user_id TEXT,
  feedback_type TEXT NOT NULL,
  content TEXT NOT NULL,
  contact TEXT,
  listing_id TEXT,
  app_key TEXT,
  status TEXT NOT NULL DEFAULT 'submitted',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_appstore_feedback_tenant
  ON appstore_feedback (tenant_id, status, created_at DESC);

-- folded migration: migrations/postgres/0004_appstore_timestamps_timestamptz.up.sql
-- 0004_appstore_timestamps_timestamptz.up.sql
-- Convert module timestamp columns from TEXT to TIMESTAMPTZ.
-- Appstore tables historically stored ISO-8601 timestamps as TEXT; row structs
-- decode them as chrono DateTime<Utc>, which sqlx only accepts from
-- TIMESTAMPTZ columns on PostgreSQL. ISO text values convert losslessly.

ALTER TABLE appstore_app ALTER COLUMN approved_at TYPE TIMESTAMPTZ USING approved_at::timestamptz;
ALTER TABLE appstore_app ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_app ALTER COLUMN deleted_at TYPE TIMESTAMPTZ USING deleted_at::timestamptz;
ALTER TABLE appstore_app ALTER COLUMN released_at TYPE TIMESTAMPTZ USING released_at::timestamptz;
ALTER TABLE appstore_app ALTER COLUMN retired_at TYPE TIMESTAMPTZ USING retired_at::timestamptz;
ALTER TABLE appstore_app ALTER COLUMN submitted_at TYPE TIMESTAMPTZ USING submitted_at::timestamptz;
ALTER TABLE appstore_app ALTER COLUMN suspended_at TYPE TIMESTAMPTZ USING suspended_at::timestamptz;
ALTER TABLE appstore_app ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_app_dependency ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_app_dependency ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_catalog_chart_snapshot ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_catalog_chart_snapshot ALTER COLUMN generated_at TYPE TIMESTAMPTZ USING generated_at::timestamptz;
ALTER TABLE appstore_catalog_collection ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_catalog_collection ALTER COLUMN ends_at TYPE TIMESTAMPTZ USING ends_at::timestamptz;
ALTER TABLE appstore_catalog_collection ALTER COLUMN starts_at TYPE TIMESTAMPTZ USING starts_at::timestamptz;
ALTER TABLE appstore_catalog_collection ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_catalog_collection_item ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_catalog_collection_item ALTER COLUMN ends_at TYPE TIMESTAMPTZ USING ends_at::timestamptz;
ALTER TABLE appstore_catalog_collection_item ALTER COLUMN starts_at TYPE TIMESTAMPTZ USING starts_at::timestamptz;
ALTER TABLE appstore_catalog_collection_localization ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_catalog_collection_localization ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_catalog_featured_slot ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_catalog_featured_slot ALTER COLUMN ends_at TYPE TIMESTAMPTZ USING ends_at::timestamptz;
ALTER TABLE appstore_catalog_featured_slot ALTER COLUMN starts_at TYPE TIMESTAMPTZ USING starts_at::timestamptz;
ALTER TABLE appstore_catalog_featured_slot ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_catalog_search_history ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_catalog_trending_term ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_catalog_trending_term ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_category ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_category ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_category_localization ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_category_localization ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_compliance_permission_disclosure ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_compliance_permission_disclosure ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_compliance_profile ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_compliance_profile ALTER COLUMN reviewed_at TYPE TIMESTAMPTZ USING reviewed_at::timestamptz;
ALTER TABLE appstore_compliance_profile ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_download_grant ALTER COLUMN consumed_at TYPE TIMESTAMPTZ USING consumed_at::timestamptz;
ALTER TABLE appstore_download_grant ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_download_grant ALTER COLUMN expires_at TYPE TIMESTAMPTZ USING expires_at::timestamptz;
ALTER TABLE appstore_download_grant ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_entitlement ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_entitlement ALTER COLUMN expires_at TYPE TIMESTAMPTZ USING expires_at::timestamptz;
ALTER TABLE appstore_entitlement ALTER COLUMN revoked_at TYPE TIMESTAMPTZ USING revoked_at::timestamptz;
ALTER TABLE appstore_entitlement ALTER COLUMN starts_at TYPE TIMESTAMPTZ USING starts_at::timestamptz;
ALTER TABLE appstore_entitlement ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_feedback ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_feedback ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_idempotency_key ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_idempotency_key ALTER COLUMN expires_at TYPE TIMESTAMPTZ USING expires_at::timestamptz;
ALTER TABLE appstore_idempotency_key ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_install_event ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_install_event ALTER COLUMN occurred_at TYPE TIMESTAMPTZ USING occurred_at::timestamptz;
ALTER TABLE appstore_listing ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_listing ALTER COLUMN deleted_at TYPE TIMESTAMPTZ USING deleted_at::timestamptz;
ALTER TABLE appstore_listing ALTER COLUMN delisted_at TYPE TIMESTAMPTZ USING delisted_at::timestamptz;
ALTER TABLE appstore_listing ALTER COLUMN published_at TYPE TIMESTAMPTZ USING published_at::timestamptz;
ALTER TABLE appstore_listing ALTER COLUMN submitted_at TYPE TIMESTAMPTZ USING submitted_at::timestamptz;
ALTER TABLE appstore_listing ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_listing_category_binding ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_listing_iap_item ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_listing_iap_item ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_listing_localization ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_listing_localization ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_listing_media ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_listing_media ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_listing_metric_snapshot ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_listing_rating ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_listing_rating ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_listing_submission ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_listing_submission ALTER COLUMN submitted_at TYPE TIMESTAMPTZ USING submitted_at::timestamptz;
ALTER TABLE appstore_listing_submission ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_listing_tag_binding ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_market_channel ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_market_channel ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_market_release ALTER COLUMN approved_at TYPE TIMESTAMPTZ USING approved_at::timestamptz;
ALTER TABLE appstore_market_release ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_market_release ALTER COLUMN last_synced_at TYPE TIMESTAMPTZ USING last_synced_at::timestamptz;
ALTER TABLE appstore_market_release ALTER COLUMN rejected_at TYPE TIMESTAMPTZ USING rejected_at::timestamptz;
ALTER TABLE appstore_market_release ALTER COLUMN released_at TYPE TIMESTAMPTZ USING released_at::timestamptz;
ALTER TABLE appstore_market_release ALTER COLUMN submitted_at TYPE TIMESTAMPTZ USING submitted_at::timestamptz;
ALTER TABLE appstore_market_release ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_moderation_appeal ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_moderation_appeal ALTER COLUMN decided_at TYPE TIMESTAMPTZ USING decided_at::timestamptz;
ALTER TABLE appstore_moderation_appeal ALTER COLUMN submitted_at TYPE TIMESTAMPTZ USING submitted_at::timestamptz;
ALTER TABLE appstore_moderation_appeal ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_moderation_decision ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_moderation_decision ALTER COLUMN decided_at TYPE TIMESTAMPTZ USING decided_at::timestamptz;
ALTER TABLE appstore_moderation_review ALTER COLUMN completed_at TYPE TIMESTAMPTZ USING completed_at::timestamptz;
ALTER TABLE appstore_moderation_review ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_moderation_review ALTER COLUMN sla_due_at TYPE TIMESTAMPTZ USING sla_due_at::timestamptz;
ALTER TABLE appstore_moderation_review ALTER COLUMN started_at TYPE TIMESTAMPTZ USING started_at::timestamptz;
ALTER TABLE appstore_moderation_review ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_publisher ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_publisher ALTER COLUMN deleted_at TYPE TIMESTAMPTZ USING deleted_at::timestamptz;
ALTER TABLE appstore_publisher ALTER COLUMN suspended_at TYPE TIMESTAMPTZ USING suspended_at::timestamptz;
ALTER TABLE appstore_publisher ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_publisher ALTER COLUMN verified_at TYPE TIMESTAMPTZ USING verified_at::timestamptz;
ALTER TABLE appstore_publisher_member ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_publisher_member ALTER COLUMN joined_at TYPE TIMESTAMPTZ USING joined_at::timestamptz;
ALTER TABLE appstore_publisher_member ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_publisher_verification ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_publisher_verification ALTER COLUMN expires_at TYPE TIMESTAMPTZ USING expires_at::timestamptz;
ALTER TABLE appstore_publisher_verification ALTER COLUMN reviewed_at TYPE TIMESTAMPTZ USING reviewed_at::timestamptz;
ALTER TABLE appstore_publisher_verification ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_regional_availability ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_regional_availability ALTER COLUMN effective_at TYPE TIMESTAMPTZ USING effective_at::timestamptz;
ALTER TABLE appstore_regional_availability ALTER COLUMN expires_at TYPE TIMESTAMPTZ USING expires_at::timestamptz;
ALTER TABLE appstore_regional_availability ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_release ALTER COLUMN approved_at TYPE TIMESTAMPTZ USING approved_at::timestamptz;
ALTER TABLE appstore_release ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_release ALTER COLUMN published_at TYPE TIMESTAMPTZ USING published_at::timestamptz;
ALTER TABLE appstore_release ALTER COLUMN retired_at TYPE TIMESTAMPTZ USING retired_at::timestamptz;
ALTER TABLE appstore_release ALTER COLUMN submitted_at TYPE TIMESTAMPTZ USING submitted_at::timestamptz;
ALTER TABLE appstore_release ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_release_artifact ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_release_artifact ALTER COLUMN package_format TYPE TIMESTAMPTZ USING package_format::timestamptz;
ALTER TABLE appstore_release_artifact ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_release_beta_invite ALTER COLUMN accepted_at TYPE TIMESTAMPTZ USING accepted_at::timestamptz;
ALTER TABLE appstore_release_beta_invite ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_release_beta_invite ALTER COLUMN invited_at TYPE TIMESTAMPTZ USING invited_at::timestamptz;
ALTER TABLE appstore_release_beta_invite ALTER COLUMN revoked_at TYPE TIMESTAMPTZ USING revoked_at::timestamptz;
ALTER TABLE appstore_release_beta_invite ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_release_channel ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_release_channel ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_release_note_localization ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_release_note_localization ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_release_rollout ALTER COLUMN completed_at TYPE TIMESTAMPTZ USING completed_at::timestamptz;
ALTER TABLE appstore_release_rollout ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_release_rollout ALTER COLUMN paused_at TYPE TIMESTAMPTZ USING paused_at::timestamptz;
ALTER TABLE appstore_release_rollout ALTER COLUMN started_at TYPE TIMESTAMPTZ USING started_at::timestamptz;
ALTER TABLE appstore_release_rollout ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_tag ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_tag ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_tag_localization ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_tag_localization ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_user_library_item ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_user_library_item ALTER COLUMN installed_at TYPE TIMESTAMPTZ USING installed_at::timestamptz;
ALTER TABLE appstore_user_library_item ALTER COLUMN last_checked_at TYPE TIMESTAMPTZ USING last_checked_at::timestamptz;
ALTER TABLE appstore_user_library_item ALTER COLUMN removed_at TYPE TIMESTAMPTZ USING removed_at::timestamptz;
ALTER TABLE appstore_user_library_item ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
ALTER TABLE appstore_user_wishlist_item ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::timestamptz;
ALTER TABLE appstore_user_wishlist_item ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::timestamptz;
